version: '3'
services:
  db2server:
    image: ibmcom/db2
    container_name: db2server
    privileged: true
    ports:
      - 50000:50000
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=lrba
      - DBNAME=LABDB
    volumes:
      - /app/lra.db2/database:/database
